apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wwww2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev-website-blog-vconsultants
    server: https://kubernetes.default.svc
  project: websites
  source:
    path: dev-master-websites/blog-vconsultants-be
    repoURL: https://github.com/hpreyers/root-websites.git
    targetRevision: HEAD
